### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [saleor/saleor-platform#124]
![image](https://user-images.githubusercontent.com/11587185/145597652-89b513f5-31f3-4b8d-84a6-919617132141.png)

Getting CORS issue on accessing dashboard from client machine.

Version : 3.0.0-a.30

**Comment by l4b4r4b4b4** [comment]
My guess is that you are trying to reach your local installation over your local network. Default settings seem to only allow requests from `localhost`. Since you are trying to access your api container over the Dashboard (Port 9000) from the IP `192.168.29.228` it doesn't allow that. 
Possible solutions would be 
1. to set the IP in `ALLOWED_CLIENT_HOSTS`, 
2. to tunnel the dashboards port to localhost over ssh and open http://localhost:9000 in your browser or 
3. to simply test your installation on the machine it is running on.

Hope this helps :)

**Comment by magul** [comment]
Hi @kaushalkumarjoshi ,

although what you want to achieve is possible (you should check suggestions from @l4b4r4b4b4 ), we don't intend to deliver that as (based on our README):

> Keep in mind this repository is for local development only and is not meant to be deployed on any production environment! If you're not a developer and just want to try out Saleor you can check our [live demo](https://demo.saleor.io/).

Closing that one as wont fix.
