### ISSUE TITLE
Revisit local dev setup with Docker

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-platform#157]
The current saleor-platform setup seems not to work correctly.

We expect a 1-command setup of the container with Saleor core and it's dependencies.

The main target as discussed with @mirekm  is a seamless setup for frontenders, who want to encapsulate Python, DB, and another core-related tooling inside containers.

One solution is to maintain a set of Dockerfiles with each tool (Dashboard, Checkout, Core...) and one or more docker-compose configs to run entire ecosystem

- [ ] Consult other issues and @peelar work
- [x] Introduce temporary fix to Docker setup
- [ ] Consider proposal by @zaiste 
- [ ] Strategic proposal / RFC on holistic dev experience of local development, cc @peelar

**Comment by lkostrowski** [comment]
Related https://github.com/saleor/saleor/issues/10104

**Comment by lkostrowski** [comment]
Related https://github.com/saleor/saleor/issues/9764

**Comment by lkostrowski** [comment]
Related https://github.com/saleor/saleor-platform/issues/154

**Comment by lkostrowski** [comment]
Related https://github.com/saleor/react-storefront/issues/263

**Comment by lkostrowski** [comment]
Related https://github.com/saleor/saleor-platform/pull/30

**Comment by peelar** [comment]
I keep reading or hearing that `saleor-platform` does not work correctly. As I am the one who mentioned some issues with it that started this whole discussion, I feel obliged to give you some context.

It's not that `saleor-platform` does not work correctly. I am confused about the actual purpose of it. I think only when we define what the use-case for running `saleor-platform` is, can we start thinking about whether it does work correctly or not.

---

Let me walk you through my first experience with setting up Saleor locally, so you can understand why I am even asking the question:

1. I begin the process of learning Saleor by going to [the documentation](https://docs.saleor.io/docs/3.x/developer)
2. Progressing through the articles, I arrive at the [Installation](https://docs.saleor.io/docs/3.x/developer/installation) article that lists the commands to clone the `saleor-platform` repository:

```
git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3
cd saleor-platform
docker-compose build
```
3. I run all the commands, and everything is working. In that sense, `saleor-platform` does work correctly. I mean, **I have to run some other scripts to apply migrations and populate the database**, so that can be improved, but it's not the end of the world, and it's not what caused my confusion.
4. So, `saleor-platform` is running, but now what? The first words in the README of `saleor-platform` are the following:
> Keep in mind this repository is for local development only and is not meant to be deployed on any production environment! 

What good comes from a setup that I can't even deploy?

Also, it says that `saleor-platform` is for local development only, but what kind of local development, really? AFAIK, the preferred way to contribute to Saleor/change something in it is to fork it. The commands above are, however, just cloning it. 

So if I can't (?) develop with `saleor-platform`, and I can't deploy it, when do I use it?

---

It is totally possible that I am missing something because I am not familiar with the open-source workflow, as well as the dev-opsy side of things. But one thing I am sure of is that we have to communicate these things better. The purpose of `saleor-platform` should not be a mystery. The preferred way to host & deploy Saleor on your own should not be either.

**Comment by lkostrowski** [comment]
I have updated local subrepos to the newest releases, everything works pretty well.

We will think with @magul if we should just update this repo (and continue updating), or we should also version it.

Some ideas are also
1. Push images to registry
2. Separate docker compose for backend-only, so if I want to use only backend, I dont want do build all frontend (slow)
3. Use makefile for scripts

**Comment by patrys** [comment]
@lkostrowski Can we consider this one closed?
