### ISSUE TITLE
I can't bootstrap with Docker.

### ISSUE THREAD

**Issue by endo-aki22** [saleor/saleor-platform#188]
I use Windows 11 and docker-desktop v4.12.0.
![2022-09-29_05-31](https://user-images.githubusercontent.com/61251512/193020686-2e4a52ec-5430-4865-ac2a-9e404b4d7da2.png)
I checked a list of ports in use.
Port 16686 is not in use.
Why did I get this error?
![2022-09-29_05-33](https://user-images.githubusercontent.com/61251512/193021046-9c66962c-1a11-44eb-996f-dc2fc6b4b077.png)
![2022-09-29_05-35](https://user-images.githubusercontent.com/61251512/193021324-0528c501-2d6f-441a-bd26-506f334b03be.png)

**Comment by lkostrowski** [comment]
@magul can you have a look?

**Comment by magul** [comment]
@endo-aki22 @lkostrowski that's the first time I see such error, but based on a last line of error logs:
```
Error response from daemon: Ports are not available: unable to list exposed ports: Get "http://unix/forwards/list": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
I'm going to assume, that's not this port being occupied, but docker VM (used on Windows) cannot retrieve list of port forwards from metadata endpoint exposed to it (see: `Get "http://unix/forwards/list": context deadline exceeded`.).

That would mean, that there's something seriously wrong with Docker installation on this Windows, or network hit some kind of bottleneck.

Don't know, why it can happened, one hypothesis (with implicit bottleneck assumtion) I have (if we intend to blame Saleor here) is that `saleor-dashboard`'s `node_modules` is huge and it already has happened to me, that I have problems staring `docker-compose up` from that repo, because something was timing out, because it cannot handle sending this whole `node_modules` by loopback interface in time. Eventually after few retries it started working.

Based on provided screenshots there's not much help we can provide, unfortunately (and TBH I don't know what exactly we would require to get to be able to help here).

**Comment by lkostrowski** [comment]
No problem @endo-aki22 . I will close the issue for now. Open new issue if you have any further problems!
