### ISSUE TITLE
Storefront live reloading not possible

### ISSUE THREAD

**Issue by shoesack** [saleor/saleor-platform#206]
Hey, i discovered Saleor a few weeks ago and want to give it a shot and try things out using this saleor-platform repo. 

Even if this is meant to be for docker dev instances it seems that live reloading isn't supported in general (for the storefront). Following the initial installation steps and enabling docker file sharing for the specific repo path doesnt solve this...i have to rebuild each time I edit some storefront code.

Even changing the docker-compose command within /react-storefront/  from `sh -c '(nginx &) && pnpm turbo run start --filter=storefront...'` to `sh -c '(nginx &) && pnpm turbo run dev --filter=storefront...'` doesnt do the trick. 

Did anybody manage to enable live reloading? 
If not, it seems I'll need to create all the services without docker in general (at least the frontend ones)

OS: MacOS 13.0 Ventura
Docker Engine: 20.10.20

**Comment by witoszekdev** [comment]
Hi, @shoesack currently live-reloading for `storefront` and `saleor-app-checkout` in Docker is unsupported (main issue we've found was Turborepo's caching). Due to this, we don't have `volumes` configured inside `docker-compose.yaml`.

For development, I'd recommend running the project outside of Docker with the instructions in README: https://github.com/saleor/react-storefront#development

**Comment by shoesack** [comment]
Hi and thanks a lot @witoszekdev 

Yes, i'm already following your proposed way on how to start the local dev server.

Anyway, probably wording of the [Readme](https://github.com/saleor/saleor-platform#with-docker-steps) should be changed as it creates a different expectation when ist says `1. We are using shared folders to enable live code reloading. Without this, Docker Compose will not start:`
