### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by bedilbek** [saleor/saleor-platform#25]
Hi.

I am curious about the problem of docker host permissions. How do you resolve docker container broken permission rules on the host machine? For example, if you create a django migration inside a container, that migration is going to be created in host binded volume too, but with the permissions of the docker container.

I also saw that you create `saleor:saleor` `user:group` inside a Dockerfile. So, does it imply that all the developers should have and use `saleor` user on their host machine in order to mitigate this problem?

Thanks!

**Comment by grll** [comment]
Hi,

Personally I run all the command from within the container so the problem of permission is not really one since I am always root user. The integration is great with VS Code and the remote-container extension btw something similar can be achieved with Pycharm.

 If you really want to use things like migration files or other generated files from outside the container then you will need to specify a user. You can specify a user using `--user` argument from docker commands.

Also in some ML pipeline I was needing to use the output of my models outside docker so I had a custom Dockerfile to automatically create a user with my local name and id at build time using `--build-args`. Let me know if you need that I can dig it out for you.
