### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by sah-anshu** [saleor/saleor-platform#56]
Hi,
I am following the steps. After docker-compose up when i try to access the site on public port. I get the error. 

Invalid Host header

Please help. Thanks in advance.

**Comment by kinvaris** [comment]
As explained in the README.md, this is not intended to run as a production setup. This is designed to run on your local machine. 

But reading from the code on saleor core: `ALLOWED_HOSTS = get_list(os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1"))`

If one should add the environment variable ALLOWED_HOSTS, with the domain name and or ip addresses, to the docker compose file in the saleor core container; you should be able to reach it.

**Comment by icanotc** [comment]
so how would we run this for production then? this is the only recommended way to install it according to the docs.

**Comment by dionysiusmarquis** [comment]
> so how would we run this for production then? this is the only recommended way to install it according to the docs.

My guess is to build the sub-modules `saleor-dashboard` and `saleor-storefront` via `npm build`. Then renaming `dockerfile: ./Dockerfile.dev` to `dockerfile: ./Dockerfile`, also remove `command: npm start -- --host 0.0.0.0` in the correstponding docker-compose.yml services. This way you are running nginx instead of a webpack dev server.

**Comment by l4b4r4b4b4** [comment]
> As explained in the README.md, this is not intended to run as a production setup. This is designed to run on your local machine.
> 
> But reading from the code on saleor core: `ALLOWED_HOSTS = get_list(os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1"))`
> 
> If one should add the environment variable ALLOWED_HOSTS, with the domain name and or ip addresses, to the docker compose file in the saleor core container; you should be able to reach it.
> 
> ```
> [user@vm saleor-2.10.2]$ grep AL Dockerfile 
> ENV ALLOWED_HOSTS localhost,127.0.0.1,192.168.1.180
> 
> root@1ea7776b17c7:/app# env | grep AL
> ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.180
> ```
> 
> For the platform, you should add the variables the the `common.env` file.
> 
> ```
> [user@vm saleor-platform]$ cat common.env 
> DATABASE_URL=postgres://saleor:saleor@db/saleor
> DEFAULT_FROM_EMAIL=noreply@example.com
> CELERY_BROKER_URL=redis://redis:6379/1
> SECRET_KEY=changeme
> ALLOWED_HOSTS=localhost,127.0.0.1,192.168.1.180
> API_URI=http://192.168.1.180:8000/graphql/
> ```
@kinvaris 
Do I understand this correctly, that I need to put both the publicly available domain as well as the internal IP of the container for the dev setup to be reachable on a remote machine with dns setup?
Well will try later anyway, but would be lovely to have a solution for this, since I have been browser the issues and discussions for a bit.
